openapi: 3.0.0
info:
  description: |
    ## Overview
    The PlusForta ERP API is for the use of our ERP customers of the BK01 application.

    ## How to use

    The process is quite simple.  You can submit an application data under the ```/application``` endpoint.  You will recieve an ```OrderID``` for this application.

    This generates an email to the end user prompting them to complete the application online and agree to the terms and conditions.

    Until the end user starts this process, the application may be updated by resubmitting the data with the ```orderId``` generated upon initial submission.

    Once the enduser completes the process, you will receive a callback at the requested URL informing you with the result of the application, either accpeted or declined.

    To end the created Contract, simply call the ```cancel``` endpoint with any of the ```orderId```, ```customId```, or ```contractNumber``` identifiers.

    *Note: If you pass more than one identifier, they will be checked against each other.  If they don't match, a failure will be generated.*

    ## How to sign up
    For more information, please contact us at info@plusforta.de.

    ## Changelog
    * v0.0.1
      * first draft
  version: "0.0.1alpha"
  title: ERP API
  contact:
    email: admin@plusforta.de
#  license:
#    name: Apache 2.0
#    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: application
    description: Submit or update an application
  - name: cancel
    description: Submit the cancellation of an existing rental deposit guarantee
servers:
  - url: 'https://oa-stage.pfdev.de/api/erp'
    description: Staging Environment usually mirrors Production, except when we are about to launch (then it's the next version)
  - url: 'https://api.kautionsfrei.de/api/erp'
    description: Production Environment (the real deal.  If you submit applications here, you will be paying for them.  :) )
  - url: 'https://oa-dev.pfdev.de/api/erp'
    description: Developer Environment (has the latest code, maybe broken)
paths:
  /application:
    post:
      tags:
        - application
      security:
        - ApiKeyAuth: []
      summary: creates an application
      operationId: createApplication
      description: |
        Allows the creation of an application
      responses:
        '200':
          description: application created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationResponse'
        '400':
          description: validation failure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationErrorResponse'
        '401':
          description: credentials for auth missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
        description: data for reservation
      callbacks:
        createContract:
          '{$request.body#/callbackUrl}':
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        customId:
                          type: string
                          description: Customer supplied ID number
                        orderId:
                          type: number
                          description: plusForta order ID
                        contractNumber:
                          type: string
                          description: R+V supplied BürgschaftsNr
                        contractStatus:
                          type: string
                          enum:
                            - accepted
                            - declined
                          description: Insurance provider response to application
                        contractStatusReason:
                          description: Reason for decline
                      required:
                        - orderId
                        - contractNumber
                        - contractStatus
                        - contractStatusReason
              responses:
                '200':
                  description: |
                    Everything is great!  Use this error code to let us know you have received the message
                '400':
                  description: |
                    Everything is bad! Use this error code to let us know you can't handle the news right now
                    and we should try again later.
  /cancel:
    post:
      tags:
        - cancel
      security:
        - ApiKeyAuth: []
      summary: cancels an existing application
      operationId: releaseObligation
      description: |
        Cancels an existing rental deposit guarantee
      responses:
        '200':
          description: obligation released
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cancelResponse'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Apikey
  schemas:
    Application:
      required:
        - callbackUrl
        - partnerId
        - lessee
        - lessor
        - apartment
        - bankAccount
      properties:
        callbackUrl:
          type: string
          description: 'URL to call upon contract creation'
          format: uri
          example: https://server.name/path
        partnerId:
          type: string
          description: predefined partner ID (maps to EPP ID)
        customId:
          type: string
          description: Customer defined ID number for end to end tracking
        orderId:
          type: number
          description: '*Must* be passed on updates, *must* be blank for new submissions'
        lessee:
          type: array
          items:
            type: object
            required:
              - firstName
              - lastName
              - email
              - address
            properties:
              gender:
                type: string
                enum:
                  - m
                  - f
                maxLength: 1
              firstName:
                type: string
                example: Max
              lastName:
                type: string
                example: Mustermann
              birthdate:
                type: string
                format: date
                example: '1984-05-01'
              email:
                type: string
                format: email
                example: 'max.mustermann@example.com'
              phone:
                type: string
                format: phonenumber
                description: 'phone number of lessee (only German numbers, starting with 0, include area code)'
                example: "030 1234567"
              address:
                type: object
                required:
                  - street
                  - houseNum
                  - zip
                  - city
                properties:
                  street:
                    type: string
                    example: Gaudystraße
                  houseNum:
                    type: string
                    example: 26A
                  zip:
                    type: string
                    example: 10439
                  city:
                    type: string
                    example: Berlin
              nationality:
                type: string
                example: DE
                format: 2 Digit ISO Country Code
        lessor:
          description: |
            Landlord information
          type: object
          properties:
            person:
              type: object
              properties:
                gender:
                  type: string
                  enum:
                    - m
                    - f
                firstName:
                  type: string
                  example: Max
                lastName:
                  type: string
                  example: Mustermann
            company:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  example: Scrooge McDuck Rental
                name2:
                  type: string
                  example: Berlin Office
            address:
              type: object
              required:
                - street
                - houseNum
                - zip
                - city
              properties:
                street:
                  type: string
                  example: Gaudystraße
                houseNum:
                  type: string
                  example: 26A
                zip:
                  type: string
                  example: 10439
                city:
                  type: string
                  example: Berlin
        apartment:
          type: object
          required:
            - sum
            - rental_date
            - move_date
            - address_street
            - address_snumber
            - address_zip
            - address_city
            - postal_dest
            - sum_rent
          properties:
            is_existing:
              description: Normally 0, 1 if Deposit has already been paid
              type: string
              enum:
                - "0"
                - "1"
            sum:
              description: 'Value of the deposit in the format: 1.000,00'
              type: string
              example: '1.500,00'
            until_temporary:
              description: 'if the rental contract is temporary (see is_temporary below), end date in the format: YYYY-MM-DD'
              example: '2020-02-01'
              type: string
            rental_date:
              description: 'Date contract was signed in the format: YYYY-MM-DD'
              example: '2019-01-15'
              type: string
            move_date:
              description: 'Move-in date in the format: YYYY-MM-DD'
              example: '2019-02-01'
              type: string
            name:
              type: string
              example: Mustermann
            first_name:
              type: string
              example: Max
            address_street:
              type: string
              example: Gaudystraße
            address_snumber:
              type: string
              example: "26A"
            address_zip:
              type: string
              example: "10439"
            address_city:
              type: string
              example: 'Berlin'
            is_temporary:
              description: 'Contract is temporary? 1 Yes, 0 No>'
              type: string
              enum:
                - "0"
                - "1"
            postal_dest:
              description: |
                Where should the guarantee document be sent: 0 current Applicant address (lessee), 1 new address (apartment), 1 Landlord's Address (lessor)
              type: string
              enum:
                - "0"
                - "1"
                - "2"
            sum_rent:
              description: 'Monthly cold rent in the format: 1.000,00'
              type: string
              example: '500,00'
        banking_account_attributes:
          type: object
          required:
            - holder_name
            - holder_firstname
            - holder_company
            - bank_name
            - iban
          properties:
            holder_name:
              type: string
              example: Mustermann
            holder_firstname:
              type: string
              example: Max
            holder_company:
              type: string
              example: Muster, GmbH
            bank_name:
              type: string
              example: DKB
            iban:
              type: string
              example: DE12500105170648489890
            payment:
              type: string
              description: '12 for monthly payments | 1 for annual payment'
              enum:
                - "1"
                - "12"
    ApplicationResponse:
      properties:
        cid:
          type: string
          example: 7kH5lXW1QIid2q+c5Eq0qg==
        state:
          type: string
          enum:
            - not_completed_not_reservation
          description: |
            * `not_completed_not_reservation` - Application is ready for submission
        id:
          type: string
          example: "10000005"
        type:
          type: string
          example: TenancyRetail
        brand:
          type: string
          example: kf
        documents:
          type: object
          example: {}
    cancelResponse:  # @todo
      properties:
        cid:
          type: string
          example: 7kH5lXW1QIid2q+c5Eq0qg==
        state:
          type: string
          enum:
            - completed_not_reservation_accepted
            - completed_not_reservation_not_accepted
            - completed_not_reservation_stopped
            - completed_not_reservation_pending
          description: |
            * `completed_not_reservation_accepted` - Application was submitted and was accepted
            * `completed_not_reservation_not_accepted` - Application was submitted and was NOT accepted
            * `completed_not_reservation_stopped` - Application was submitted but a technical failure occurred.
            * `completed_not_reservation_pending` - Application was submitted but manual processing required.
        id:
          type: string
          example: "10000005"
        type:
          type: string
          example: TenancyRetail
        brand:
          type: string
          example: kf
          enum:
            - kf
        documents:
          type: object
          properties:
            tenancy_reservation_complete:
              type: string
              example: >-
                […]/documents/5?file_location_hash=c5ffb9896bf5df93a454acb89737c79776c13e00af595e77cbce07dc27c5f39f
    ApplicationErrorResponse:
      properties:
        error:
          type: string
          example: 'lessee_attributes.terms_accepted : must be accepted'
        error_struct:
          description: |
            a list of fields that have errors. For the above example, it would be a field named 'lessee_attributes.terms_accepted' with the value of an array, with a single string, 'must be accepted'
          type: object
          # This could be better. See https://swagger.io/docs/specification/data-models/dictionaries/
          # the returned object looks like this:
          # {
          #   "error": "lessee_attributes.terms_accepted : must be accepted",
          #   "error_struct": {
          #     "lessee_attributes.terms_accepted": [
          #       "must be accepted"
          #     ]
          #   }
          # }
          additionalProperties: true
    Error:
      type: object
      properties:
        # code:
        #   type: string
        message:
          type: string
      required:
        # - code
        - message
    Unauthorized:
      type: object
      properties:
        error:
          example: credentials for auth missing
          type: string

  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
D
